image: python:latest

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest test.py
  only:
    - branches

deploy:
  stage: deploy

  before_script:
    - curl -L https://fly.io/install.sh | sh

  script:
    - export FLY_API_TOKEN = $FLY_API_TOKEN
    # - /root/.fly/bin/flyctl auth login -t --access-token $FLY_API_TOKEN
    - /root/.fly/bin/flyctl deploy
  only:
    - develop
