image: python

stages:
  - test
  - deploy

# Job test
test:
  stage: test
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python -m unittest test.py


# Job deploy
deploy:
  stage: deploy
  script:
    - echo "Deploy"
  needs: ["test"]
  only:
    - develop
