image: alpine

stages:
  - test
  - deploy

# Job test
test:
  stage: test
  before_script:
    - apk add --no-cache python3
    - python3 install -r requirements.txt
  script:
    - python -m unittest test.py

# Job deploy
deploy:
  stage: deploy
  before_script:
    - apk add --no-cache curl
    # Télécharger et installer flyctl
    - curl -L https://fly.io/install.sh | sh
    # Ajouter flyctl au chemin
    - export FLYCTL_INSTALL="$HOME/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"
    - flyctl version
  script:
    - echo "Deploy"
  needs: ["test"]
  only:
    - develop
